"""One-time script: download Loughran-McDonald Master Dictionary
and generate lexicon.py with combined word lists."""

import urllib.request, csv, io, json, sys

# ── Download LM dictionary from Google Drive ──
file_id = '1iq2RUf8qGFEAk1g8wQntP3habOnR3fXF'
url = f'https://drive.google.com/uc?export=download&id={file_id}'
print(f'Downloading LM dictionary ({url})...')
resp = urllib.request.urlopen(url, timeout=120)
content = resp.read().decode('utf-8')
reader = csv.DictReader(io.StringIO(content))
rows = list(reader)
print(f'Downloaded {len(rows)} rows')

def is_set(val):
    v = val.strip()
    return v not in ('', '0', '-2020')

# Extract LM sentiment words
lm_positive = set()
lm_negative = set()
for r in rows:
    word = r['Word'].strip().lower()
    if is_set(r['Positive']):
        lm_positive.add(word)
    if is_set(r['Negative']):
        lm_negative.add(word)

print(f'LM positive: {len(lm_positive)}  LM negative: {len(lm_negative)}')

# ── Our custom headline-specific additions ──
custom_positive = {
    "revenue", "growth", "beats", "beat", "profit", "upgrade", "upgraded",
    "bullish", "dividend", "earnings", "rally", "outperform", "outperformed",
    "strong", "record", "positive", "raised", "expansion", "guidance",
    "buy", "growing", "profitable", "gains", "surge", "recovery",
    "momentum", "opportunity", "innovation", "confidence", "optimistic",
    "breakthrough", "leader", "leadership", "outlook", "accelerate",
    "accelerated", "accelerating", "uptick", "upside",
    "awarded", "partnership", "partnered", "exceed", "exceeded",
}

custom_negative = {
    "missing", "miss", "lawsuit", "loss", "risk", "downgrade", "downgraded",
    "debt", "bankruptcy", "bearish", "fine", "penalty", "investigation",
    "regulatory", "decline", "fall", "drop", "sell", "below", "weak",
    "warning", "cut", "lower", "fail", "negative", "volatility",
    "short", "underperform", "underperformed", "layoff", "fraud",
    "brutal", "verdict", "scandal", "probe", "controversy",
    "crisis", "liability", "overvalued", "suspended",
    "delay", "delays", "worst", "trouble", "damage", "deficit",
    "settlement", "charges", "impairment", "restructuring", "setback", "setbacks",
}

critical_negative = {
    "verdict", "lawsuit", "fraud", "scandal", "bankruptcy",
    "investigation", "penalty", "settlement", "crisis", "liability",
}

# Combine: LM + custom (custom words override any LM sentiment)
final_positive = lm_positive | custom_positive
final_negative = lm_negative | custom_negative

# Remove words that are in both (they cancel out — keep our custom assignment)
both = final_positive & final_negative
if both:
    print(f'Words in BOTH lists: {both}')
    # Remove from both — these are ambiguous
    final_positive -= both
    final_negative -= both

# Add critical_negative back to negative (it's a subset for weight boosting)
# They should already be in final_negative via custom_negative or lm_negative

print(f'FINAL positive: {len(final_positive)}  negative: {len(final_negative)}')
print(f'Critical-negative: {len(critical_negative)} (subset of negative)')

# Generate lexicon.py
lines = [
    "# Auto-generated by gen_lexicon.py from Loughran-McDonald Master Dictionary (1993-2025)",
    "# Loughran & McDonald (2011), Journal of Finance. https://sraf.nd.edu/",
    "#",
    f"# Positive: {len(final_positive)} words ({len(lm_positive)} from LM + {len(custom_positive)} custom headline additions)",
    f"# Negative: {len(final_negative)} words ({len(lm_negative)} from LM + {len(custom_negative)} custom headline additions)",
    "# Critical-negative: 10 words (subset for weight boost)",
    "",
    "",
    "POSITIVE_LEXICON = {",
]

# Format positive words (indented, 10 per line)
pos_sorted = sorted(final_positive)
for i in range(0, len(pos_sorted), 10):
    chunk = pos_sorted[i:i+10]
    line = "    " + ", ".join(f'"{w}"' for w in chunk) + ","
    lines.append(line)

lines.append("}")
lines.append("")

lines.append("")
lines.append("NEGATIVE_LEXICON = {")

neg_sorted = sorted(final_negative)
for i in range(0, len(neg_sorted), 10):
    chunk = neg_sorted[i:i+10]
    line = "    " + ", ".join(f'"{w}"' for w in chunk) + ","
    lines.append(line)

lines.append("}")
lines.append("")

lines.append("")
lines.append("CRITICAL_NEGATIVE_LEXICON = {")
crit_sorted = sorted(critical_negative)
for i in range(0, len(crit_sorted), 10):
    chunk = crit_sorted[i:i+10]
    line = "    " + ", ".join(f'"{w}"' for w in chunk) + ","
    lines.append(line)

lines.append("}")
lines.append("")

with open('lexicon.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
    f.write('\n')

print('Written to lexicon.py')
print(f'File size: {sum(len(l) for l in lines)} chars')
